### ISSUE TITLE
Colmar Academy Project Review

### ISSUE THREAD

**Issue by mp1pro** [tremckinley/colmar-capstone#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 4/4
* _Comment(s):_ The HTML structure is properly organized and grouped perfectly.
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_  4/4
* _Comment(s):_ Both visual layouts are professionally executed.
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_  4/4
* _Comment(s):_ The responsive design transitioned smoothly between the 3 media queries. Perfect use of comments to help organize the code.
 
### Criteria 4: Visual Design 
* _Score Level:_ 4/4
* _Comment(s):_ The color scheme looks appealing. The hover effects are very nice. The border designs are on point too.
 
### Overall Score: 16/16

Great Job. The project exceeds the required expectations. 
```

**Comment by tremckinley** [comment]
Thank you very much!
